Repository TurkNet/design-system, pull requests merged in 2021-12, with the labels that each got.

#193 Release
  src/components/Table/index.tsx
Labels: patch

#195 icon custom style fix
  src/components/Icon/index.tsx
  src/components/Icon/styled.ts
Labels: bug

#196 Release
  .storybook/preview-head.html
  src/components/Icon/index.tsx
  src/components/Icon/styled.ts
  src/stories/Icon.stories.tsx
Labels: patch

#198 Release
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
  src/components/Table/index.tsx
  src/components/Table/styled.ts
  src/stories/Table.stories.tsx
Labels: bug, patch

#199 added semi bold to placeholder when is active
  src/components/Input/styled.ts
Labels: bug

#202 Release
  src/components/Icon/index.tsx
  src/components/Icon/styled.ts
  src/components/Input/styled.ts
  src/components/Table/styled.ts
  src/components/Typography/index.tsx
  src/components/Typography/styled.ts
  src/stories/Icon.stories.tsx
  src/stories/Table.stories.tsx
  src/stories/Typograhpy.stories.tsx
Labels: bug, enhancement, patch

#203 added space props from styled system to tag component
  src/components/Tag/styled.ts
  src/stories/Tag.stories.tsx
Labels: enhancement

#208 box component get position and flex props from styled system
  src/components/Box/styled.ts
Labels: enhancement

#210 space props added badge and alert
  src/components/Alert/styled.ts
  src/components/Badge/styled.ts
Labels: enhancement

#212 Release
  src/components/Alert/styled.ts
  src/components/Badge/styled.ts
  src/components/Box/styled.ts
  src/components/Tag/styled.ts
  src/components/Typography/styled.ts
  src/shared/global.js
  src/stories/Tag.stories.tsx
Labels: bug, patch

#214 Release
  src/components/Select/index.tsx
Labels: bug, patch

#217 Release
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
  src/stories/SearchSelect.stories.tsx
  src/stories/Select.stories.tsx
Labels: bug, patch

#221 Select overlay fix
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
Labels: bug

#222 Release
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
Labels: patch

#224 add span variant
  src/components/Typography/index.tsx
  src/components/Typography/styled.ts
  src/stories/Typograhpy.stories.tsx
Labels: enhancement

#230 Datepicker refactor
  package.json
  src/components/Button/index.tsx
  src/components/DateInput/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/styled.ts
  src/stories/DateInput.stories.tsx
  tsconfig.json
Labels: bug

#231 fix selected value in datepicker
  src/components/DateInput/index.tsx
Labels: bug

#234 Release
  package.json
  src/components/Accordion/styled.ts
  src/components/Button/index.tsx
  src/components/DateInput/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/styled.ts
  src/components/Tabs/Tab.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/styled.ts
  src/components/Typography/index.tsx
  src/components/Typography/styled.ts
  src/stories/Accordion.stories.tsx
  src/stories/DateInput.stories.tsx
  src/stories/Tabs.stories.tsx
  src/stories/Typograhpy.stories.tsx
  tsconfig.json
Labels: bug, patch

#245 hotfix v0.5.21
  .gitignore
Labels: patch

#246 Release config
  .github/workflows/push.yml
  package.json
  scripts/release.sh
Labels: minor

#250 Release
  .gitignore
  CHANGELOG.md
  package.json
  scripts/release.sh
Labels: bug, patch

#251 release fix
  scripts/release.sh
Labels: patch

#253 release fix
  scripts/release.sh
Labels: bug, patch

#254 Release/v0.7.1
  package.json
  scripts/release.sh
  src/components/Accordion/AccordionItem.tsx
Labels: patch

#255 release bugfix
  .husky/.gitignore
  .husky/_/husky.sh
  package.json
Labels: patch

#257 Release v0.7.7
  CHANGELOG.md
  package.json
Labels: patch

#258 Release
  .github/workflows/push.yml
  CHANGELOG.md
  package.json
  scripts/release.sh
Labels: patch
