Repository TurkNet/design-system, pull requests merged in 2022-01, with the labels that each got.

#262 React Selact
  package.json
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
  src/stories/SearchSelect.stories.tsx
  src/stories/Select.stories.tsx
Labels: bug, patch

#263 Release
  CHANGELOG.md
  package.json
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
  src/components/Select/styled.ts
  src/stories/SearchSelect.stories.tsx
  src/stories/Select.stories.tsx
Labels: patch

#266 Release
  .github/workflows/push.yml
Labels: patch

#269 change border color
  src/components/Input/styled.ts
  src/components/Select/styled.ts
Labels: enhancement

#270 change default cursor type to inherit
  src/components/Icon/styled.ts
  src/components/Typography/styled.ts
Labels: bug

#271 Checkbox changes
  src/components/Checkbox/styled.ts
Labels: bug

#272 Added to modal closeOnClickOutside
  src/components/Modal/index.tsx
Labels: enhancement

#275 replace tr chars
  src/components/Select/index.tsx
  src/stories/Select.stories.tsx
Labels: enhancement

#277 popover icon check and input icon is centered now
  src/components/Input/styled.ts
  src/components/Popover/index.tsx
  src/components/Popover/styled.ts
  src/components/Tooltip/styled.ts
  src/stories/Popover.stories.tsx
  src/stories/Tooltip.stories.tsx
Labels: bug, enhancement

#279 change types and add toString to filter
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
Labels: bug

#281 add variant props to textarea
  src/components/Input/index.tsx
  src/components/Textarea/index.tsx
  src/components/Textarea/styled.ts
  src/stories/Textarea.stories.tsx
Labels: bug

#290 release v0.7.12
  .github/workflows/push.yml
  package.json
  scripts/release.sh
Labels: patch, release

#292 Release/v0.7.12-1 (#291)
  package.json
Labels: patch

#293 Release fix
  package.json
Labels: bug

#294 Release fix
  package.json
Labels: bug

#297 change value type
  src/components/Select/SearchSelect.tsx
  src/components/Select/index.tsx
Labels: bug

#298 add width prop to button
  src/components/Button/styled.ts
Labels: enhancement

#302 Select overlay z index
  src/components/Select/styled.ts
  src/stories/Select.stories.tsx
Labels: bug

#304 label filter check
  src/components/Select/index.tsx
Labels: bug

#307 remove first item margin
  src/components/Breadcrumb/styled.ts
Labels: bug

#313 change checkbox location
  src/components/Checkbox/styled.ts
Labels: bug

#315 add check icon remove bg add height
  src/components/OverflowMenu/OverflowMenuItem.tsx
  src/components/OverflowMenu/styled.ts
  src/stories/OverflowMenu.stories.tsx
Labels: enhancement

#316 Collapse fix
  src/components/Collapse/index.tsx
  src/components/Collapse/styled.ts
  src/stories/Collapse.stories.tsx
Labels: bug
